services:
  - type: web
    name: gym-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
